version: 2
jobs:
  build-centos:
    docker:
      - image: centos:latest
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_centos.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=el$(rpm -E %centos)
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-fedora33:
    docker:
      - image: fedora:33
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_fedora.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=f$(rpm -E %fedora)
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-opensusetumbleweed:
    docker:
      - image: opensuse/tumbleweed
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_opensuse.sh
      - run:
          name: Build
          command: if [ -e /etc/os-release ]; then . /etc/os-release; else . /usr/lib/os-release; fi && ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=suse$VERSION_ID
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-debian10:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_debian.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=debian$(lsb_release -r -s)
      - run:
          name: Alien
          command: alien -k -d build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT *.deb $UPLOAD_USER@$UPLOAD_HOST:.
  build-ubuntu2010:
    docker:
      - image: ubuntu:20.10
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_debian.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=ubuntu$(lsb_release -r -s)
      - run:
          name: Alien
          command: alien -k -d build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT *.deb $UPLOAD_USER@$UPLOAD_HOST:.
workflows:
  version: 2
  build_all:
    jobs:
      - build-fedora33
      - build-opensusetumbleweed
      - build-ubuntu2010
#      - build-centos
#      - build-debian10
